rm -f main/main.cpp
echo -e "/* DO NOT EDIT THIS FILE */" > main/main.cpp
echo -e "#include \"test/${testFile}\"" >> main/main.cpp
echo -e "extern \"C\"" >> main/main.cpp
echo -e "{" >> main/main.cpp
echo -e "\tvoid app_main();" >> main/main.cpp
echo -e "}" >> main/main.cpp
rm -f -r "build/main"
make -j all